# Generated by Django 5.2.2 on 2025-06-12 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_varified',
            new_name='otp_verified',
        ),
    ]
