# Generated by Django 5.2 on 2025-06-24 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_slag_movie_slug'),
        ('theaters', '0002_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.DateTimeField()),
                ('silver_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimond_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.theater')),
            ],
        ),
    ]
