# Generated by Django 5.2.2 on 2025-07-02 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Showtime',
            new_name='showtime',
        ),
    ]
