# Generated by Django 5.2.2 on 2025-06-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, choices=[('Action', 'Action'), ('Horror', 'Horror'), ('Thriler', 'Thriler'), ('Comedy', 'Comedy'), ('Drama', 'Drama')], max_length=255, null=True)),
                ('language', models.CharField(blank=True, choices=[('Bengali', 'Bengali'), ('English', 'English'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada')], max_length=255, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('upcoming', 'upcoming'), ('released', 'released')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_image', models.ImageField(blank=True, null=True, upload_to='movies/')),
            ],
        ),
    ]
