# Generated by Django 5.2.2 on 2025-06-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slag',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
