# Generated by Django 5.2.2 on 2025-06-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_slag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='slag',
            new_name='slug',
        ),
    ]
